import { Injectable, inject } from '@angular/core';
import { EditorService } from './editor.service';
import { WireframeElement, WireframeProject } from '../models/element.model';
import JSZip from 'jszip';

@Injectable({
    providedIn: 'root'
})
export class ExportService {
    private editor = inject(EditorService);

    async exportProject() {
        const assets = this.generateProjectAssets();
        const zip = new JSZip();

        zip.file('index.html', assets.html);
        zip.file('style.css', assets.css);
        zip.file('robots.txt', assets.robots);
        zip.file('sitemap.xml', assets.sitemap);
        zip.file('README.md', assets.readme);

        const content = await zip.generateAsync({ type: 'blob' });
        this.downloadFile(`${assets.projectName.replace(/\s+/g, '_')}_export.zip`, content);
    }

    previewProject() {
        const assets = this.generateProjectAssets();
        const previewHtml = assets.html.replace(
            '</head>',
            `<style>${assets.css}</style></head>`
        );

        const blob = new Blob([previewHtml], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        window.open(url, '_blank');
    }

    private generateProjectAssets() {
        const project = this.editor.project();
        return {
            projectName: project.name,
            html: this.generateHTML(project),
            css: this.generateCSS(project),
            robots: this.generateRobotsTxt(),
            sitemap: this.generateSitemap(project),
            readme: this.generateReadme(project)
        };
    }

    private generateHTML(project: WireframeProject): string {
        const elementsHtml = project.rootElements
            .map(id => this.renderElementToHtml(project.elements[id], project.elements))
            .join('\n');

        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${project.name} - WireGen Export</title>
    <meta name="description" content="Wireframe export generated by WireGen">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header class="project-header">
        <h1>${project.name}</h1>
    </header>
    <main class="canvas-export">
        ${elementsHtml}
    </main>
    <footer class="project-footer">
        <p>Generated by WireGen</p>
    </footer>
</body>
</html>`;
    }

    private renderElementToHtml(el: WireframeElement, all: Record<string, WireframeElement>): string {
        const childrenHtml = (el.children || [])
            .map(id => this.renderElementToHtml(all[id], all))
            .join('\n');

        const tagName = this.getTagName(el.type);
        const attributes = this.getAttributes(el);
        const content = el.content || '';

        // If it's an image, we might want to render an <img> tag inside
        if (el.type === 'image') {
            return `<figure class="element element-${el.id}">
        <img src="${el.imageUrl || 'https://via.placeholder.com/150'}" alt="${el.name}" style="width:100%; height:100%; object-fit: cover;">
        ${childrenHtml}
      </figure>`;
        }

        return `<${tagName} class="element element-${el.id}" ${attributes}>
    ${content}
    ${childrenHtml}
</${tagName}>`;
    }

    private getTagName(type: string): string {
        switch (type) {
            case 'button': return 'button';
            case 'input': return 'input';
            case 'text': return 'p';
            case 'image': return 'figure';
            case 'container': return 'div';
            default: return 'div';
        }
    }

    private getAttributes(el: WireframeElement): string {
        if (el.type === 'input') {
            return `type="text" placeholder="${el.placeholder || ''}"`;
        }
        return '';
    }

    private generateCSS(project: WireframeProject): string {
        let css = `
* { box-sizing: border-box; }
body { margin: 0; font-family: 'Inter', -apple-system, sans-serif; display: flex; flex-direction: column; min-height: 100vh; background: #f8fafc; color: #1e293b; }
.project-header, .project-footer { background: #ffffff; padding: 24px; text-align: center; border-bottom: 1px solid #e2e8f0; }
.project-header h1 { margin: 0; font-size: 1.5rem; font-weight: 700; }
.project-footer { border-bottom: none; border-top: 1px solid #e2e8f0; font-size: 0.875rem; color: #64748b; margin-top: auto; }
.canvas-export { flex: 1; position: relative; background: #fff; width: 1200px; min-height: 800px; margin: 48px auto; box-shadow: 0 10px 25px -5px rgba(0,0,0,0.1); border-radius: 12px; overflow: hidden; border: 1px solid #e2e8f0; }
.element { position: absolute; display: flex; align-items: center; justify-content: center; text-align: center; overflow: hidden; }
input { width: 100%; border: 1px solid #cbd5e1; padding: 8px; border-radius: 4px; }
button { cursor: pointer; border: none; font-weight: 500; }
`;

        Object.values(project.elements).forEach(el => {
            const bWidth = el.styles.borderWidth || 0;
            css += `
.element-${el.id} {
  width: ${el.styles.width}px;
  height: ${el.styles.height}px;
  top: ${el.styles.top}px;
  left: ${el.styles.left}px;
  background-color: ${el.styles.backgroundColor || 'transparent'};
  color: ${el.styles.color || '#000'};
  border-radius: ${el.styles.borderRadius || 0}px;
  border: ${bWidth}px solid ${el.styles.borderColor || '#cbd5e1'};
  padding: ${el.styles.padding || 8}px;
  font-size: ${el.styles.fontSize || 14}px;
}
`;
        });

        return css;
    }

    private generateRobotsTxt(): string {
        return `User-agent: *
Allow: /
Sitemap: sitemap.xml`;
    }

    private generateSitemap(project: WireframeProject): string {
        return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://example.com/</loc>
    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
    <priority>1.0</priority>
  </url>
</urlset>`;
    }

    private generateReadme(project: WireframeProject): string {
        return `# ${project.name}

This project was generated using **WireGen**, a modern wireframe editor.

## Contents
- \`index.html\`: Semantic HTML layout
- \`style.css\`: Layout and component styling
- \`robots.txt\`: SEO configuration
- \`sitemap.xml\`: Site structure for search engines

## How to use
Simply open \`index.html\` in any modern web browser to view your wireframe.
`;
    }

    private downloadFile(filename: string, blob: Blob) {
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        link.click();
        window.URL.revokeObjectURL(url);
    }
}
