import { Injectable, inject } from '@angular/core';
import { EditorService } from './editor.service';
import { WireframeElement, WireframeProject } from '../models/element.model';

@Injectable({
    providedIn: 'root'
})
export class ExportService {
    private editor = inject(EditorService);

    exportProject() {
        const project = this.editor.project();
        const html = this.generateHTML(project);
        const css = this.generateCSS(project);
        const robots = this.generateRobotsTxt();
        const sitemap = this.generateSitemap(project);
        const readme = this.generateReadme(project);

        // For a real app, we would use a library like jszip
        // For this demo, we'll log the result and provide a download function
        this.downloadFile('index.html', html);
        this.downloadFile('style.css', css);
        this.downloadFile('robots.txt', robots);
        this.downloadFile('sitemap.xml', sitemap);
        this.downloadFile('README.md', readme);
    }

    private generateHTML(project: WireframeProject): string {
        const elementsHtml = project.rootElements
            .map(id => this.renderElementToHtml(project.elements[id], project.elements))
            .join('\n');

        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${project.name} - WireGen Export</title>
    <meta name="description" content="Wireframe export generated by WireGen">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>${project.name}</h1>
    </header>
    <main class="canvas-export">
        ${elementsHtml}
    </main>
    <footer>
        <p>Generated by WireGen</p>
    </footer>
</body>
</html>`;
    }

    private renderElementToHtml(el: WireframeElement, all: Record<string, WireframeElement>): string {
        const childrenHtml = (el.children || [])
            .map(id => this.renderElementToHtml(all[id], all))
            .join('\n');

        const tagName = this.getTagName(el.type);
        const attributes = this.getAttributes(el);
        const content = el.content || '';

        return `<${tagName} class="element element-${el.id}" ${attributes}>
    ${content}
    ${childrenHtml}
</${tagName}>`;
    }

    private getTagName(type: string): string {
        switch (type) {
            case 'button': return 'button';
            case 'input': return 'input';
            case 'text': return 'p';
            case 'image': return 'figure';
            case 'container': return 'div';
            default: return 'div';
        }
    }

    private getAttributes(el: WireframeElement): string {
        if (el.type === 'input') {
            return `type="text" placeholder="${el.placeholder || ''}"`;
        }
        return '';
    }

    private generateCSS(project: WireframeProject): string {
        let css = `
body { margin: 0; font-family: sans-serif; display: flex; flex-direction: column; min-height: 100vh; }
header, footer { background: #f3f4f6; padding: 20px; text-align: center; }
main { flex: 1; position: relative; background: #fff; width: 1200px; height: 800px; margin: 0 auto; overflow: hidden; }
.element { position: absolute; box-sizing: border-box; }
`;

        Object.values(project.elements).forEach(el => {
            css += `
.element-${el.id} {
  width: ${el.styles.width}px;
  height: ${el.styles.height}px;
  top: ${el.styles.top}px;
  left: ${el.styles.left}px;
  background-color: ${el.styles.backgroundColor || 'transparent'};
  color: ${el.styles.color || '#000'};
  border-radius: ${el.styles.borderRadius || 0}px;
  padding: ${el.styles.padding || 0}px;
  display: flex;
  align-items: center;
  justify-content: center;
}
`;
        });

        return css;
    }

    private generateRobotsTxt(): string {
        return `User-agent: *
Allow: /
Sitemap: sitemap.xml`;
    }

    private generateSitemap(project: WireframeProject): string {
        return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://example.com/</loc>
    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
    <priority>1.0</priority>
  </url>
</urlset>`;
    }

    private generateReadme(project: WireframeProject): string {
        return `# ${project.name}

This project was generated using **WireGen**, a modern wireframe editor.

## Contents
- \`index.html\`: Semantic HTML layout
- \`style.css\`: Layout and component styling
- \`robots.txt\`: SEO configuration
- \`sitemap.xml\`: Site structure for search engines

## How to use
Simply open \`index.html\` in any modern web browser to view your wireframe.
`;
    }

    private downloadFile(filename: string, content: string) {
        const blob = new Blob([content], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        link.click();
        window.URL.revokeObjectURL(url);
    }
}
